apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
data:
  index.html: |
    <html>
    <h1>Welcome to production</h1>
    </br>
    <h1>This is a working nginx website on kubernetes! </h1>
    </html>
