---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base
commonLabels:
  app: nginx-deployment
resources:
  - nginxDeploy.yaml
  - service.yaml
  - index-html-configmap.yaml
